version: "4.7.1"

services:
  balance-service:
     build: .
     container_name: bs
     restart: on-failure
     ports:
     - 5000:5000
     depends_on:
     - db

  db:
    build: 
     context: db
    container_name: psql_db
    environment:
      POSTGRES_DB: "aedb"
      POSTGRES_USER: "super"
      POSTGRES_PASSWORD: "1212"
    ports:
      - "5432:5432"
  db_test:
    build: 
     context: db
    container_name: psql_db_tests
    environment:
      POSTGRES_DB: "aedb"
      POSTGRES_USER: "super"
      POSTGRES_PASSWORD: "1212"
    ports:
      - "15432:5432"