run:
	go run ./cmd/api

build:
	@go mod tidy
	CGO_ENABLED=0 go build -o bin/main ./cmd/api

swag:
	swag init -g cmd/api/main.go

test:
	PG_DSN=$(PG_DSN) VALUES=$(VALUES) go test -v ./...

docker-start:
	sudo docker compose build --no-cache
	sudo docker compose up 